CLASS /MINDSET/ZERROR_LOG_TEST  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS /MINDSET/ZERROR_LOG_TEST IMPLEMENTATION.
ENDCLASS.
